const BET_STATUS = {
  NOT_EXISTING: 'NOT EXISTING',
  MISSING_X_BETTOR: 'MISSING X BETTOR',
  MISSING_O_BETTOR: 'MISSING O BETTOR',
  WITHDRAWN: 'WITHDRAWN',
  FIXED: 'FIXED',
  PAYEDOUT: 'PAID OUT'
};
export default BET_STATUS;
