const BET_STATUS = {
  NOT_EXISTING: 'NOT_EXISTING',
  MISSING_X_BETTOR: 'MISSING_X_BETTOR',
  MISSING_O_BETTOR: 'MISSING_O_BETTOR',
  WITHDRAWN: 'WITHDRAWN',
  FIXED: 'FIXED',
  PAYEDOUT: 'PAYEDOUT'
};
export default BET_STATUS;
