const GAME_STATUS = {
    NOT_EXISTING: 'NOT EXISTING',
    EMPTY: 'EMPTY',
    WAITING_FOR_O: 'WAITING FOR O',
    WAITING_FOR_X: 'WAITING FOR X',
    READY: 'READY TO START',
    X_HAS_TURN: 'X HAS TURN',
    O_HAS_TURN: 'O HAS TURN',
    WINNER_X: 'WINNER X',
    WINNER_O: 'WINNER O',
    DRAW: 'DRAW'
};

export default GAME_STATUS;