const STATUS = {
  GAME_CREATED: 'CREATED',
  GAME_JOINED: 'JOINED',
  GAME_STARTED: 'STARTED',
  MOVE_MADE: 'PLAYED',
  JOINED_BET: 'JOINED_BET',
  PLACED_BET: 'PLACED_BET',
  WITHDRAWN_BET: 'WITHDRAWN_BET'
};

export default STATUS;
