const STATUS = {
  GAME_CREATED: 'CREATE GAME',
  GAME_JOINED: 'JOIN GAME',
  GAME_STARTED: 'START GAME',
  MOVE_MADE: 'PLAY',
  JOINED_BET: 'JOIN BET',
  PLACED_BET: 'PLACE BET',
  WITHDRAWN_BET: 'WITHDRAW BET'
};

export default STATUS;
